PREFIX dc: <http://purl.org/dc/elements/1.1/>
prefix powla: <http://purl.org/powla/powla.owl#>

# List all the corpora currently available in the LiLa Knowledge Base
SELECT ?subject ?Textual_Resource_title
WHERE {
  ?subject ?predicate powla:Corpus ;
           dc:title ?Textual_Resource_title
}order by ?Textual_Resource_title