PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX powla: <http://purl.org/powla/powla.owl#>

#Selects those synsets in the Latin WordNet that are evoked by more than 50 lexical entries of the LWN

SELECT ?synset ?synset_definition (COUNT(?synset) AS ?count)
WHERE
{
  ?LWN_LE ontolex:evokes ?synset .
  ?synset rdfs:label ?synset_label ;
          skos:definition ?synset_definition .
  FILTER regex(?synset_label, "^Wordnet Synset.*")
}
group by ?synset ?synset_definition
having (count(?synset) > 40)