PREFIX lila: <http://lila-erc.eu/ontologies/lila/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix powla: <http://purl.org/powla/powla.owl#>
prefix lemma: <http://lila-erc.eu/data/id/lemma#>


# Retrieve the lemmas in the lemmaBank with specific Part-of-Speech (e.g., NOUN)
SELECT ?lemma ?wrs  where {
  {
    SELECT ?lemma (GROUP_CONCAT(DISTINCT ?wr ;separator=", ") AS ?wrs)
    where{
      ?lemma rdf:type lila:Lemma;
             lila:hasPOS lila:noun ;
             ontolex:writtenRep ?wr
    } group by ?lemma
  }
} order by ?wrs

