PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?lex ?title WHERE {
  ?lex ?pred lime:Lexicon ;
  		dcterms:title ?title
}order by ?title
