###############################################
# TITLE: Velez's Dictionary - definitions with "mulher" (woman)
# DESCRIPTION: Searches for all lemmas in LiLa LemmaBank whose definition in the Velez's dictionary includes the word "mulher" (woman).
###############################################
PREFIX lila: <http://lila-erc.eu/ontologies/lila/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lime: <http://www.w3.org/ns/lemon/lime#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>

# Searches for all lemmas in LiLa LemmaBank whose definition in the Velez's dictionary includes the word "mulher" (woman).

SELECT (group_concat(distinct ?lemmaWrittenRep ; separator=", ") as ?lemmas) ?PoS ?definition ?senseURI 
WHERE {   
  <http://lila-erc.eu/data/lexicalResources/LatinPortuguese/Velez/Lexicon> lime:entry  ?lexentry.
  ?lexentry ontolex:canonicalForm ?lemmaURI ;
            ontolex:sense ?senseURI .
  ?lemmaURI rdfs:label ?lemma ;
            lila:hasPOS ?PoS ;
            ontolex:writtenRep ?lemmaWrittenRep .
  ?senseURI rdf:type ontolex:LexicalSense;
      <http://www.w3.org/2004/02/skos#definition> ?definition.
  FILTER regex(?definition, "mulher")
}order by ?PoS ?lemmas ?senseURI 

# NOTES
# For changing the queried word, replace "mulher" by the desired one at line 19.